#_____  _____  _____  __  __  ____   _____
#/  _  \/  _  \/  _  \/   /  \/  _/  /  ___>
#|  _  <|  _  <|  _  ||  /\  ||  |---|___  |
#\_____/\__|\_/\__|__/\__/\__/\_____/<_____/
#
#_____  _____  _____  _____  _____  _____  _____
#/   __\/  _  \|  _  \/  _  \/  _  \/  _  \/  ___>
#|   __||  |  ||  |  ||  _  <|  |  ||   __/|___  |
#\_____/\___\ \|_____/\__|\_/\_____/\__/   <_____/

dropPercentage: 0.5  # Percentage of items to drop 1=100%